language: java
jdk: oraclejdk8
install: true
sudo: false

env:
  global:
  - SONATYPE_USERNAME=benoitx
  - secure: MtZwtUKZtF83MDYsKbZeyJn0R9xvSFBA9jJpk1wQXJ/zZCQsNbBJGm8ez8l5x++tGwX5BvbEeH3rqWrul9gNLcNG5PXUnar5rAHUFAHnEr3OuPfKogkOGMXxK0xXWzeKIJx5nDAAPvqlMe7lGOogA60ZFfQM3CdHwbWlNo/xVVI=
  - secure: DSPCcO+Ny49IioFE8AHUyAEIVCP+j+5xJSyj3z9TvFfSgvLVrVPbhb62dkvheA0j2gaIOWVqivmqp3ZLzCDavyUZFzKtpp1Jo1SwcrG0kKG2dR/abQ8Vf2ct1n+5l0ebOQlAxVZnJpbAoKNYl3aT7wrOkrVtEAB4dUNaKUDJ7aU

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

deploy:
    on:
      branch: travis-testing
    skip_cleanup: true
    provider: script
    script: "python travis/addServer.py && $HOME/.m2/settings.xml && mvn deploy"