language: java
jdk: oraclejdk8
install: true
sudo: false

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

deploy:
    on:
      branch: travis-testing
    skip_cleanup: true
    provider: script
    script: "cp ./travis/settings.xml $HOME/.m2/settings.xml && cat $HOME/.m2/settings.xml && mvn deploy"